// Code generated by protoc-gen-go. DO NOT EDIT.
// source: queue.proto

package queue

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Priority int32

const (
	Priority_LOW  Priority = 0
	Priority_HIGH Priority = 1
)

var Priority_name = map[int32]string{
	0: "LOW",
	1: "HIGH",
}
var Priority_value = map[string]int32{
	"LOW":  0,
	"HIGH": 1,
}

func (x Priority) String() string {
	return proto.EnumName(Priority_name, int32(x))
}
func (Priority) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_queue_3f1cc34dac06a765, []int{0}
}

// Puts a new message in the queue
type EnqueueRequest struct {
	// The actual task to enqueue
	Message []byte `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// The priority of the task
	Priority Priority `protobuf:"varint,2,opt,name=priority,proto3,enum=Priority" json:"priority,omitempty"`
	// What capabilities are required to handle the task
	RequiredCapabilities []string `protobuf:"bytes,3,rep,name=requiredCapabilities,proto3" json:"requiredCapabilities,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnqueueRequest) Reset()         { *m = EnqueueRequest{} }
func (m *EnqueueRequest) String() string { return proto.CompactTextString(m) }
func (*EnqueueRequest) ProtoMessage()    {}
func (*EnqueueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_queue_3f1cc34dac06a765, []int{0}
}
func (m *EnqueueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnqueueRequest.Unmarshal(m, b)
}
func (m *EnqueueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnqueueRequest.Marshal(b, m, deterministic)
}
func (dst *EnqueueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnqueueRequest.Merge(dst, src)
}
func (m *EnqueueRequest) XXX_Size() int {
	return xxx_messageInfo_EnqueueRequest.Size(m)
}
func (m *EnqueueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnqueueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnqueueRequest proto.InternalMessageInfo

func (m *EnqueueRequest) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *EnqueueRequest) GetPriority() Priority {
	if m != nil {
		return m.Priority
	}
	return Priority_LOW
}

func (m *EnqueueRequest) GetRequiredCapabilities() []string {
	if m != nil {
		return m.RequiredCapabilities
	}
	return nil
}

type EnqueueResponse struct {
	// The id of the created task
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnqueueResponse) Reset()         { *m = EnqueueResponse{} }
func (m *EnqueueResponse) String() string { return proto.CompactTextString(m) }
func (*EnqueueResponse) ProtoMessage()    {}
func (*EnqueueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_queue_3f1cc34dac06a765, []int{1}
}
func (m *EnqueueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnqueueResponse.Unmarshal(m, b)
}
func (m *EnqueueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnqueueResponse.Marshal(b, m, deterministic)
}
func (dst *EnqueueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnqueueResponse.Merge(dst, src)
}
func (m *EnqueueResponse) XXX_Size() int {
	return xxx_messageInfo_EnqueueResponse.Size(m)
}
func (m *EnqueueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnqueueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnqueueResponse proto.InternalMessageInfo

func (m *EnqueueResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Removes a single message from the queue
type PopRequest struct {
	// What capabilities the client has available
	AvailableCapabilities []string `protobuf:"bytes,1,rep,name=availableCapabilities,proto3" json:"availableCapabilities,omitempty"`
	// If the server should wait for a message to come in, before returning
	// with a response
	WaitForMessage bool `protobuf:"varint,2,opt,name=waitForMessage,proto3" json:"waitForMessage,omitempty"`
	// An optional reference id that will be passed back with
	// the PopResponse, incase the client is multiplexing the
	// socket
	RefId                int32    `protobuf:"varint,3,opt,name=refId,proto3" json:"refId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PopRequest) Reset()         { *m = PopRequest{} }
func (m *PopRequest) String() string { return proto.CompactTextString(m) }
func (*PopRequest) ProtoMessage()    {}
func (*PopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_queue_3f1cc34dac06a765, []int{2}
}
func (m *PopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PopRequest.Unmarshal(m, b)
}
func (m *PopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PopRequest.Marshal(b, m, deterministic)
}
func (dst *PopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PopRequest.Merge(dst, src)
}
func (m *PopRequest) XXX_Size() int {
	return xxx_messageInfo_PopRequest.Size(m)
}
func (m *PopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PopRequest proto.InternalMessageInfo

func (m *PopRequest) GetAvailableCapabilities() []string {
	if m != nil {
		return m.AvailableCapabilities
	}
	return nil
}

func (m *PopRequest) GetWaitForMessage() bool {
	if m != nil {
		return m.WaitForMessage
	}
	return false
}

func (m *PopRequest) GetRefId() int32 {
	if m != nil {
		return m.RefId
	}
	return 0
}

type PopResponse struct {
	// True if there was a message available
	HadResult bool `protobuf:"varint,3,opt,name=hadResult,proto3" json:"hadResult,omitempty"`
	// The actual message to process
	Message []byte `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// The id of the message
	// Should be returned with the acknowledge request
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// The refId from the request
	RefId                int32    `protobuf:"varint,4,opt,name=refId,proto3" json:"refId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PopResponse) Reset()         { *m = PopResponse{} }
func (m *PopResponse) String() string { return proto.CompactTextString(m) }
func (*PopResponse) ProtoMessage()    {}
func (*PopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_queue_3f1cc34dac06a765, []int{3}
}
func (m *PopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PopResponse.Unmarshal(m, b)
}
func (m *PopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PopResponse.Marshal(b, m, deterministic)
}
func (dst *PopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PopResponse.Merge(dst, src)
}
func (m *PopResponse) XXX_Size() int {
	return xxx_messageInfo_PopResponse.Size(m)
}
func (m *PopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PopResponse proto.InternalMessageInfo

func (m *PopResponse) GetHadResult() bool {
	if m != nil {
		return m.HadResult
	}
	return false
}

func (m *PopResponse) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *PopResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PopResponse) GetRefId() int32 {
	if m != nil {
		return m.RefId
	}
	return 0
}

type AcknowledgeRequest struct {
	// The id of the message to acknowledge
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcknowledgeRequest) Reset()         { *m = AcknowledgeRequest{} }
func (m *AcknowledgeRequest) String() string { return proto.CompactTextString(m) }
func (*AcknowledgeRequest) ProtoMessage()    {}
func (*AcknowledgeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_queue_3f1cc34dac06a765, []int{4}
}
func (m *AcknowledgeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcknowledgeRequest.Unmarshal(m, b)
}
func (m *AcknowledgeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcknowledgeRequest.Marshal(b, m, deterministic)
}
func (dst *AcknowledgeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcknowledgeRequest.Merge(dst, src)
}
func (m *AcknowledgeRequest) XXX_Size() int {
	return xxx_messageInfo_AcknowledgeRequest.Size(m)
}
func (m *AcknowledgeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AcknowledgeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AcknowledgeRequest proto.InternalMessageInfo

func (m *AcknowledgeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Wraps the requests for easier parsing on the socket layer
type RequestWrapper struct {
	// Types that are valid to be assigned to Message:
	//	*RequestWrapper_Enqueue
	//	*RequestWrapper_Pop
	//	*RequestWrapper_Acknowledge
	Message              isRequestWrapper_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *RequestWrapper) Reset()         { *m = RequestWrapper{} }
func (m *RequestWrapper) String() string { return proto.CompactTextString(m) }
func (*RequestWrapper) ProtoMessage()    {}
func (*RequestWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_queue_3f1cc34dac06a765, []int{5}
}
func (m *RequestWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestWrapper.Unmarshal(m, b)
}
func (m *RequestWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestWrapper.Marshal(b, m, deterministic)
}
func (dst *RequestWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestWrapper.Merge(dst, src)
}
func (m *RequestWrapper) XXX_Size() int {
	return xxx_messageInfo_RequestWrapper.Size(m)
}
func (m *RequestWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_RequestWrapper proto.InternalMessageInfo

type isRequestWrapper_Message interface {
	isRequestWrapper_Message()
}

type RequestWrapper_Enqueue struct {
	Enqueue *EnqueueRequest `protobuf:"bytes,1,opt,name=enqueue,proto3,oneof"`
}
type RequestWrapper_Pop struct {
	Pop *PopRequest `protobuf:"bytes,2,opt,name=pop,proto3,oneof"`
}
type RequestWrapper_Acknowledge struct {
	Acknowledge *AcknowledgeRequest `protobuf:"bytes,3,opt,name=acknowledge,proto3,oneof"`
}

func (*RequestWrapper_Enqueue) isRequestWrapper_Message()     {}
func (*RequestWrapper_Pop) isRequestWrapper_Message()         {}
func (*RequestWrapper_Acknowledge) isRequestWrapper_Message() {}

func (m *RequestWrapper) GetMessage() isRequestWrapper_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *RequestWrapper) GetEnqueue() *EnqueueRequest {
	if x, ok := m.GetMessage().(*RequestWrapper_Enqueue); ok {
		return x.Enqueue
	}
	return nil
}

func (m *RequestWrapper) GetPop() *PopRequest {
	if x, ok := m.GetMessage().(*RequestWrapper_Pop); ok {
		return x.Pop
	}
	return nil
}

func (m *RequestWrapper) GetAcknowledge() *AcknowledgeRequest {
	if x, ok := m.GetMessage().(*RequestWrapper_Acknowledge); ok {
		return x.Acknowledge
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*RequestWrapper) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _RequestWrapper_OneofMarshaler, _RequestWrapper_OneofUnmarshaler, _RequestWrapper_OneofSizer, []interface{}{
		(*RequestWrapper_Enqueue)(nil),
		(*RequestWrapper_Pop)(nil),
		(*RequestWrapper_Acknowledge)(nil),
	}
}

func _RequestWrapper_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*RequestWrapper)
	// message
	switch x := m.Message.(type) {
	case *RequestWrapper_Enqueue:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Enqueue); err != nil {
			return err
		}
	case *RequestWrapper_Pop:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Pop); err != nil {
			return err
		}
	case *RequestWrapper_Acknowledge:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Acknowledge); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("RequestWrapper.Message has unexpected type %T", x)
	}
	return nil
}

func _RequestWrapper_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*RequestWrapper)
	switch tag {
	case 1: // message.enqueue
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EnqueueRequest)
		err := b.DecodeMessage(msg)
		m.Message = &RequestWrapper_Enqueue{msg}
		return true, err
	case 2: // message.pop
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PopRequest)
		err := b.DecodeMessage(msg)
		m.Message = &RequestWrapper_Pop{msg}
		return true, err
	case 3: // message.acknowledge
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AcknowledgeRequest)
		err := b.DecodeMessage(msg)
		m.Message = &RequestWrapper_Acknowledge{msg}
		return true, err
	default:
		return false, nil
	}
}

func _RequestWrapper_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*RequestWrapper)
	// message
	switch x := m.Message.(type) {
	case *RequestWrapper_Enqueue:
		s := proto.Size(x.Enqueue)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RequestWrapper_Pop:
		s := proto.Size(x.Pop)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RequestWrapper_Acknowledge:
		s := proto.Size(x.Acknowledge)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ResponseWrapper struct {
	// Types that are valid to be assigned to Message:
	//	*ResponseWrapper_Enqueue
	//	*ResponseWrapper_Pop
	Message              isResponseWrapper_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ResponseWrapper) Reset()         { *m = ResponseWrapper{} }
func (m *ResponseWrapper) String() string { return proto.CompactTextString(m) }
func (*ResponseWrapper) ProtoMessage()    {}
func (*ResponseWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_queue_3f1cc34dac06a765, []int{6}
}
func (m *ResponseWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseWrapper.Unmarshal(m, b)
}
func (m *ResponseWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseWrapper.Marshal(b, m, deterministic)
}
func (dst *ResponseWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseWrapper.Merge(dst, src)
}
func (m *ResponseWrapper) XXX_Size() int {
	return xxx_messageInfo_ResponseWrapper.Size(m)
}
func (m *ResponseWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseWrapper proto.InternalMessageInfo

type isResponseWrapper_Message interface {
	isResponseWrapper_Message()
}

type ResponseWrapper_Enqueue struct {
	Enqueue *EnqueueResponse `protobuf:"bytes,1,opt,name=enqueue,proto3,oneof"`
}
type ResponseWrapper_Pop struct {
	Pop *PopResponse `protobuf:"bytes,2,opt,name=pop,proto3,oneof"`
}

func (*ResponseWrapper_Enqueue) isResponseWrapper_Message() {}
func (*ResponseWrapper_Pop) isResponseWrapper_Message()     {}

func (m *ResponseWrapper) GetMessage() isResponseWrapper_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *ResponseWrapper) GetEnqueue() *EnqueueResponse {
	if x, ok := m.GetMessage().(*ResponseWrapper_Enqueue); ok {
		return x.Enqueue
	}
	return nil
}

func (m *ResponseWrapper) GetPop() *PopResponse {
	if x, ok := m.GetMessage().(*ResponseWrapper_Pop); ok {
		return x.Pop
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ResponseWrapper) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ResponseWrapper_OneofMarshaler, _ResponseWrapper_OneofUnmarshaler, _ResponseWrapper_OneofSizer, []interface{}{
		(*ResponseWrapper_Enqueue)(nil),
		(*ResponseWrapper_Pop)(nil),
	}
}

func _ResponseWrapper_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ResponseWrapper)
	// message
	switch x := m.Message.(type) {
	case *ResponseWrapper_Enqueue:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Enqueue); err != nil {
			return err
		}
	case *ResponseWrapper_Pop:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Pop); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ResponseWrapper.Message has unexpected type %T", x)
	}
	return nil
}

func _ResponseWrapper_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ResponseWrapper)
	switch tag {
	case 1: // message.enqueue
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EnqueueResponse)
		err := b.DecodeMessage(msg)
		m.Message = &ResponseWrapper_Enqueue{msg}
		return true, err
	case 2: // message.pop
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PopResponse)
		err := b.DecodeMessage(msg)
		m.Message = &ResponseWrapper_Pop{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ResponseWrapper_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ResponseWrapper)
	// message
	switch x := m.Message.(type) {
	case *ResponseWrapper_Enqueue:
		s := proto.Size(x.Enqueue)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ResponseWrapper_Pop:
		s := proto.Size(x.Pop)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*EnqueueRequest)(nil), "EnqueueRequest")
	proto.RegisterType((*EnqueueResponse)(nil), "EnqueueResponse")
	proto.RegisterType((*PopRequest)(nil), "PopRequest")
	proto.RegisterType((*PopResponse)(nil), "PopResponse")
	proto.RegisterType((*AcknowledgeRequest)(nil), "AcknowledgeRequest")
	proto.RegisterType((*RequestWrapper)(nil), "RequestWrapper")
	proto.RegisterType((*ResponseWrapper)(nil), "ResponseWrapper")
	proto.RegisterEnum("Priority", Priority_name, Priority_value)
}

func init() { proto.RegisterFile("queue.proto", fileDescriptor_queue_3f1cc34dac06a765) }

var fileDescriptor_queue_3f1cc34dac06a765 = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0x8f, 0xd3, 0x30,
	0x10, 0xc5, 0xe3, 0x64, 0x97, 0x26, 0x93, 0x55, 0x5a, 0x99, 0x45, 0xca, 0x01, 0x44, 0x88, 0x00,
	0x45, 0x80, 0x72, 0x08, 0x48, 0x9c, 0x01, 0x01, 0x59, 0x09, 0xc4, 0xca, 0x97, 0x3d, 0xbb, 0x64,
	0x28, 0x56, 0x43, 0xed, 0x3a, 0x09, 0x15, 0x37, 0x2e, 0x7c, 0x11, 0x3e, 0x29, 0xaa, 0x9b, 0x7f,
	0x0d, 0xd5, 0x1e, 0x3d, 0x6f, 0xa4, 0xf7, 0x7b, 0xcf, 0x03, 0xfe, 0xb6, 0xc1, 0x06, 0x53, 0xa5,
	0x65, 0x2d, 0xe3, 0x3f, 0x04, 0x82, 0xf7, 0x1b, 0x33, 0x61, 0xb8, 0x6d, 0xb0, 0xaa, 0x69, 0x08,
	0xb3, 0x1f, 0x58, 0x55, 0x7c, 0x85, 0x21, 0x89, 0x48, 0x72, 0xc1, 0xba, 0x27, 0x7d, 0x02, 0xae,
	0xd2, 0x42, 0x6a, 0x51, 0xff, 0x0a, 0xed, 0x88, 0x24, 0x41, 0xe6, 0xa5, 0xd7, 0xed, 0x80, 0xf5,
	0x12, 0xcd, 0xe0, 0x52, 0xe3, 0xb6, 0x11, 0x1a, 0x8b, 0x77, 0x5c, 0xf1, 0xa5, 0x28, 0x45, 0x2d,
	0xb0, 0x0a, 0x9d, 0xc8, 0x49, 0x3c, 0x76, 0x52, 0x8b, 0x1f, 0xc1, 0xbc, 0xc7, 0xa8, 0x94, 0xdc,
	0x54, 0x48, 0x03, 0xb0, 0x45, 0x61, 0x10, 0x3c, 0x66, 0x8b, 0x22, 0xfe, 0x4d, 0x00, 0xae, 0xa5,
	0xea, 0x30, 0x5f, 0xc1, 0x3d, 0xfe, 0x93, 0x8b, 0x92, 0x2f, 0x4b, 0x3c, 0xb2, 0x21, 0xc6, 0xe6,
	0xb4, 0x48, 0x9f, 0x42, 0xb0, 0xe3, 0xa2, 0xfe, 0x20, 0xf5, 0xe7, 0x36, 0xe3, 0x3e, 0x88, 0xcb,
	0x26, 0x53, 0x7a, 0x09, 0xe7, 0x1a, 0xbf, 0x5d, 0x15, 0xa1, 0x13, 0x91, 0xe4, 0x9c, 0x1d, 0x1e,
	0xf1, 0x1a, 0x7c, 0x43, 0xd0, 0x12, 0xde, 0x07, 0xef, 0x3b, 0x2f, 0x18, 0x56, 0x4d, 0x59, 0x9b,
	0x45, 0x97, 0x0d, 0x83, 0x5b, 0x7a, 0x3c, 0x24, 0xb3, 0xbb, 0x64, 0x83, 0xd9, 0xd9, 0xd8, 0xec,
	0x31, 0xd0, 0x37, 0x5f, 0xd7, 0x1b, 0xb9, 0x2b, 0xb1, 0x58, 0xf5, 0xbf, 0x33, 0x6d, 0xe5, 0x2f,
	0x81, 0xa0, 0xd5, 0x6e, 0x34, 0x57, 0x0a, 0x35, 0x7d, 0x0e, 0x33, 0x3c, 0x74, 0x69, 0xf6, 0xfc,
	0x6c, 0x9e, 0x1e, 0x7f, 0x71, 0x6e, 0xb1, 0x6e, 0x83, 0x3e, 0x04, 0x47, 0x49, 0x65, 0x60, 0xfc,
	0xcc, 0x4f, 0x87, 0x82, 0x73, 0x8b, 0xed, 0x15, 0xfa, 0x1a, 0x7c, 0x3e, 0x60, 0x98, 0x98, 0x7e,
	0x76, 0x37, 0xfd, 0x1f, 0x2d, 0xb7, 0xd8, 0x78, 0xf3, 0xad, 0xd7, 0xe7, 0x8f, 0x4b, 0x98, 0x77,
	0xa5, 0x75, 0x90, 0x2f, 0xa6, 0x90, 0x8b, 0x74, 0x72, 0x00, 0x63, 0xca, 0x68, 0x4c, 0x79, 0x91,
	0x8e, 0x3e, 0xa1, 0xc5, 0x1c, 0xb9, 0x3d, 0x7b, 0x00, 0x6e, 0x77, 0x95, 0x74, 0x06, 0xce, 0xa7,
	0x2f, 0x37, 0x0b, 0x8b, 0xba, 0x70, 0x96, 0x5f, 0x7d, 0xcc, 0x17, 0x64, 0x79, 0xc7, 0x5c, 0xfe,
	0xcb, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x89, 0x69, 0x73, 0x08, 0x03, 0x00, 0x00,
}
